[env:esp32dev]
platform  = espressif32
board     = esp32dev
framework = arduino

; Serial monitor baud rate
monitor_speed = 115200

; Libraries
lib_deps =
    mikalhart/TinyGPSPlus @ ^1.0.3
    bblanchon/ArduinoJson @ ^7.0.0
    ricmoo/qrcode @ ^0.0.1

; Build flags
build_flags =
    -DCORE_DEBUG_LEVEL=1
